# Generated by Django 5.2 on 2025-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_input', models.TextField()),
                ('bot_reply', models.TextField()),
                ('feedback', models.CharField(choices=[('positive', '👍'), ('negative', '👎')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
