# Generated by Django 5.2 on 2025-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithus', '0002_chatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfeedback',
            name='intent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='urgency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
