# Generated by Django 5.2 on 2025-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='short punchline for service card', max_length=300, null=True)),
                ('description', models.TextField(help_text='Detailed description of what this service offers')),
                ('features', models.JSONField(default=list, help_text='List of bullet points for deliverables')),
                ('category', models.CharField(choices=[('ai_automation', 'AI-Powered Automation & Agents'), ('data_platform', 'Data Engineering & Intelligence'), ('business_insight', 'Business Intelligence & Analytics'), ('web_development_support', 'Custom Web Development & Support')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
