# Generated by Django 5.2 on 2025-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai_automation', 'AI Agent / Chatbot'), ('data_engineering', 'ETL & Data Pipeline'), ('dashboard', 'BI Dashboard & Analytics'), ('automation', 'Task Automation'), ('web', 'Web App / Admin Panel')], default='ai_automation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(default=list, help_text='Bullet points of what this project does'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text="e.g. ['Python', 'Airflow', 'SQL']"),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
