# Generated by Django 5.2 on 2025-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category_project_features_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
