# Generated by Django 5.2 on 2025-04-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
