# Generated by Django 5.2 on 2025-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default='Bhaskar Dwivedi', max_length=100),
            preserve_default=False,
        ),
    ]
