# Generated by Django 5.2 on 2025-06-25 16:39

import portfolio.aboutus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_aboutus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='current_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='experience_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.aboutus.models.upload_to_profile),
        ),
    ]
