# Generated by Django 5.2 on 2025-06-25 18:21

import django.db.models.deletion
import portfolio.aboutus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_aboutus_current_focus_aboutus_experience_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='experience_list',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='aboutus_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.aboutus.models.upload_to_profile),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.aboutus.models.upload_to_hero),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_tech', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='aboutus.aboutus')),
            ],
        ),
    ]
