# Generated by Django 5.2 on 2025-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_remove_aboutus_experience_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
