# Generated by Django 5.2 on 2025-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_experience_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
