# Generated by Django 5.2 on 2025-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('service', 'Service'), ('both', 'Both')], default='project', max_length=10),
        ),
    ]
